
package retrieveform;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersistentFormRetrieve1", targetNamespace = "http://retrieveForm/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersistentFormRetrieve1 {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "SearchForm")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SearchForm", targetNamespace = "http://retrieveForm/", className = "retrieveform.SearchForm")
    @ResponseWrapper(localName = "SearchFormResponse", targetNamespace = "http://retrieveForm/", className = "retrieveform.SearchFormResponse")
    public List<String> searchForm(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
