
package retrieveform;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersistentFormRetrieve1Service", targetNamespace = "http://retrieveForm/", wsdlLocation = "http://localhost:8080/Swe645AssignmentEJB/PersistentFormRetrieve1?wsdl")
public class PersistentFormRetrieve1Service
    extends Service
{

    private final static URL PERSISTENTFORMRETRIEVE1SERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSISTENTFORMRETRIEVE1SERVICE_EXCEPTION;
    private final static QName PERSISTENTFORMRETRIEVE1SERVICE_QNAME = new QName("http://retrieveForm/", "PersistentFormRetrieve1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Swe645AssignmentEJB/PersistentFormRetrieve1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSISTENTFORMRETRIEVE1SERVICE_WSDL_LOCATION = url;
        PERSISTENTFORMRETRIEVE1SERVICE_EXCEPTION = e;
    }

    public PersistentFormRetrieve1Service() {
        super(__getWsdlLocation(), PERSISTENTFORMRETRIEVE1SERVICE_QNAME);
    }

    public PersistentFormRetrieve1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSISTENTFORMRETRIEVE1SERVICE_QNAME, features);
    }

    public PersistentFormRetrieve1Service(URL wsdlLocation) {
        super(wsdlLocation, PERSISTENTFORMRETRIEVE1SERVICE_QNAME);
    }

    public PersistentFormRetrieve1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSISTENTFORMRETRIEVE1SERVICE_QNAME, features);
    }

    public PersistentFormRetrieve1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersistentFormRetrieve1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersistentFormRetrieve1
     */
    @WebEndpoint(name = "PersistentFormRetrieve1Port")
    public PersistentFormRetrieve1 getPersistentFormRetrieve1Port() {
        return super.getPort(new QName("http://retrieveForm/", "PersistentFormRetrieve1Port"), PersistentFormRetrieve1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersistentFormRetrieve1
     */
    @WebEndpoint(name = "PersistentFormRetrieve1Port")
    public PersistentFormRetrieve1 getPersistentFormRetrieve1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://retrieveForm/", "PersistentFormRetrieve1Port"), PersistentFormRetrieve1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSISTENTFORMRETRIEVE1SERVICE_EXCEPTION!= null) {
            throw PERSISTENTFORMRETRIEVE1SERVICE_EXCEPTION;
        }
        return PERSISTENTFORMRETRIEVE1SERVICE_WSDL_LOCATION;
    }

}
